Factura/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('facturacion.urls')),
    path('', include('catalogo.urls')),
]

catalogo/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('catalogo/', views.catalogo, name="catalogo"),
    path('annadir-catalogo/', views.stock, name="createcatalogo"),
]

catalogo/models.py
from django.db import models

# Create your models here.
class Catalogo(models.Model):
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    imagen = models.CharField(max_length=500)
    tamanno = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    moneda = models.CharField(max_length=10)
    fecha = models.DateTimeField(auto_now_add=True)

facturacion/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=200, default="Cliente")
    numero_wsp = models.CharField(max_length=12, unique=True)

    def __str__(self):
        return self.numero_wsp


class Producto(models.Model):
    fecha = models.DateField(auto_now_add=True)
    nombre_producto = models.CharField(max_length=200)
    enlace_temu = models.CharField(max_length=300)
    cantidad = models.IntegerField(default=1)
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    tipo_pago = models.CharField(max_length=200)
    peso = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    encargado = models.BooleanField(default=False)
    recibido = models.BooleanField(default=False)
    entregado = models.BooleanField(default=False)
    factura = models.ForeignKey(Cliente, on_delete=models.CASCADE, to_field='numero_wsp')
    cambio_cup = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    cambio_mlc = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    nota = models.TextField(default="")


    @property
    def total(self):
        return self.precio * self.cantidad
    def total_cup(self):
        return self.total * self.cambio_cup
    def total_mlc(self):
        return self.total * self.cambio_mlc
    
    

    def fecha_formateada(self):
        return self.fecha.strftime('%d/%m/%Y')
    


catalogo/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import Catalogo
import json

# Create your views here.


def home(request):
    catalogo = Catalogo.objects.all().order_by('-pk')
    return render(request, 'home.html',{
        'productos': catalogo,
    })


def catalogo(request):
    catalogo = Catalogo.objects.all().order_by('-pk')
    return render(request, "catalogo/catalogo.html", {
        'productos': catalogo,
    })


def stock(request):
    if request.method == 'GET':
        return render(request, "catalogo/crearcatalogo.html")
    if request.method == 'POST':
        data = json.loads(request.body)
        
        nombre_producto = data.get('nombre_producto')
        imagen_producto = data.get('imagen_producto')
        precio = data.get('precio')
        moneda_producto = data.get('moneda_producto')
        tamanno = data.get('tamanno')

        # Crea una nueva instancia del producto y guárdala
        product = Catalogo(
            nombre=nombre_producto,
            imagen=imagen_producto,
            precio=precio,
            moneda=moneda_producto,
            tamanno=tamanno,
        )
        
        product.save()
        
        return JsonResponse({'success': True})
    
    return JsonResponse({'success': False}, status=400)



def modstock(request, product_id):
    catalogo = Catalogo.objects.get(pk=product_id)


    return render(request, "catalogo/modcatalogo.html", {
        'producto': catalogo,
    })

templates/catalogo/catalogo.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<div class="col-lg-9 justify-content-center border-end">
    <div class="container row">
    {% for producto in productos %}
    <div class="col-md-4 mb-3">
    <div class="card d-grid">
        <img src="{{producto.imagen}}" class="card-img-top img-fluid" alt="{{producto.nombre}}" height="200" width="200">
      
        <div class="card-body">
          <h5 class="card-title">{{producto.nombre}}</h5>
          <p class="card-text"><b>Precio:</b>{{producto.precio}} {{producto.moneda}}<br><small><b>Tamaño:</b> {{producto.tamanno}}cm</small></p>
          <a href="http://api.whatsapp.com/send?phone=5359806171&text=👋 Hola%2C Deseo comprar el siguiente producto%3A {{producto.nombre}}" class="btn btn-success">Ir a Comprar</a>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
</div>


<div class="col-sm-3 justify-content-end">
    <div>
      <h3>Ultimas Publicaciones</h3>
      
      <ul>
        {% for producto in productos|slice:":5" %}
        <li>
          {{producto.nombre}}, Precio: {{producto.precio}} {{producto.moneda}}
        </li>
        {% endfor %}
      </ul>
    </div>
    <div>
    <div class="img justify-content-center">
      <img src="{% static 'logo.png' %}" alt="logo" width="100%">
    </div>
      <div class="text">
        <p>
          Tienda de articulos anime-gamer por encargos
        </p>
      </div>
    </div>
</div>
{% endblock %}

templates/catalogo/crearcatalogo.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<div class="col">
    <div>
    <h1>
        Añadir nuevo producto
        <a href="{% url 'home' %}" class="btn btn-warning mt-2 me-2 float-end">Salir</a>
    </h1>
</div>
    <div class="row">
    <div class="justify-content-start col-lg-8 border-end">
        <form method="post">
            {% csrf_token %}
            <div>
                <button class="btn btn-outline-danger mt-2 rounded-pill float-start" type="reset" id="btn-reset">Limpiar Campos</button>
                <Button class="btn btn-outline-success mt-2 rounded-pill float-end" type="submit" id="btn-preview">
        Preview
        </Button></div>
        <div>
        <table class="table">
            <tr>
                <th class="col-3">
                    Nombre del Producto:
                </th>
                <td class="col" colspan="5">
                    <input class="form-control" type="text" name="nombre_producto" maxlength="200" required id="id_nombre_producto" placeholder="Nombre del Producto">
                </td>
            </tr>
            <tr>
                <th class="col-3">
                    Imagen del Producto:
                </th>
                <td class="col" colspan="5">
                    <input class="form-control" type="text" name="imagen_producto" maxlength="500" required id="id_imagen_producto" placeholder="Url de la Imagen del Producto">
                </td>
            </tr>
            <tr>
                <th class="col-3">
                    Precio del Producto:
                </th>
                <td class="col">
                    <input class="form-control" type="number" name="precio" value="0" step="0.01" required id="id_precio">
                </td>
                <th class="col">
                    Moneda de Pago:
                </th>
                <td class="col">
                    <input class="form-control" type="text" name="moneda_producto" maxlength="10" required id="id_moneda_producto" placeholder="Moneda de Pago del Producto">
                </td>
                <th class="col">
                    Tamaño del Producto:
                </th>
                <td class="col">
                    <div class="input-group mb-3">
                    <input class="form-control" type="number" name="tamanno" value="0" step="0.1" required id="id_tamanno"><span class="input-group-text">cm</span></div>
                </td>
                
            </tr>
        </table>
    </div>

        </form>
        

    </div>
    <div class="col-4">
        <div>
            <Button id="addToCatalog" class="btn btn-outline-success mt-2 rounded-pill">
            + Añadir al Catalogo
            </Button></div>
        <div id="preview"></div>
        
</div>
</div>

<div id="successModal" class="modal" style="display:none;">
    <div class="modal-content">
        <p>Factura guardada con éxito.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md">
        <a href="{% url 'createcatalogo' %}" class="btn btn-outline-success btn-sm me-md-2 rounded-pill" id="newInvoiceBtn">Añadir nuevo producto</a>
        <a href="{% url 'productos' %}" class="btn btn-outline-success btn-sm me-md-2 rounded-pill" id="viewProductsBtn">Revisar Catalogo</a>
    </div>
    </div>
</div>

<style>
    /* Estilos básicos para el modal */
    .modal {
        display: none; 
        position: fixed; 
        z-index: 1; 
        left: 0;
        top: 0;
        width: 100%; 
        height: 100%; 
        overflow: auto; 
        background-color: rgb(0,0,0); 
        background-color: rgba(0,0,0,0.4); 
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; 
        padding: 20px;
        border: 1px solid #888;
        width: 40%; 
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }
</style>
<script src="{% static 'preview.js' %}"></script>
{% endblock %}

templates/catalogo/modcatalogo.html
{% extends 'Base/base.html' %}
{% block content %}


{% endblock %}