Factura/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('facturacion.urls')),
    path('', include('catalogo.urls')),
]

catalogo/models.py
from django.db import models

# Create your models here.
class Catalogo(models.Model):
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    imagen = models.CharField(max_length=500)
    tamanno = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    moneda = models.CharField(max_length=10)
    fecha = models.DateTimeField(auto_now_add=True)

facturacion/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=200, default="Cliente")
    numero_wsp = models.CharField(max_length=12, unique=True)

    def __str__(self):
        return self.numero_wsp


class Producto(models.Model):
    fecha = models.DateField(auto_now_add=True)
    nombre_producto = models.CharField(max_length=200)
    enlace_temu = models.CharField(max_length=300)
    cantidad = models.IntegerField(default=1)
    precio = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    tipo_pago = models.CharField(max_length=200)
    peso = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    encargado = models.BooleanField(default=False)
    recibido = models.BooleanField(default=False)
    entregado = models.BooleanField(default=False)
    factura = models.ForeignKey(Cliente, on_delete=models.CASCADE, to_field='numero_wsp')
    cambio_cup = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    cambio_mlc = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    nota = models.TextField(default="")


    @property
    def total(self):
        return self.precio * self.cantidad
    def total_cup(self):
        return self.total * self.cambio_cup
    def total_mlc(self):
        return self.total * self.cambio_mlc
    
    

    def fecha_formateada(self):
        return self.fecha.strftime('%d/%m/%Y')
    


templates/facturas/clientes.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}


        <!-- Lista de Clientes -->
        <div class="col-md-3 border-end" id="clientes-list">
            <h2>Clientes</h2>
            <ul class="list-group" id="client-list">
                {% for cliente in clientes %}
                <li class="btn-group mt-2">
                <button class="btn btn-outline-success" data-numero-wsp="{{ cliente.numero_wsp }}">
                    <b>{{ cliente.nombre }}</b><br> 
                    +53{{ cliente.numero_wsp }}</button>
                
                </li>
                {% endfor %}
                
                </table>
            </ul>
        </div>
        <!-- Detalles de Productos -->
<div class="col-md-7" id="productos-details">
    <h2>Productos</h2>
    <div id="productos-container">
        <p>Selecciona un cliente para ver sus productos.</p>                
    </div>
</div>

        

<style>
    .fecha-producto {
        margin-top: 20px;
        border-top: 1px solid #ccc;
        padding-top: 10px;
    }
</style>

<script src="{% static 'clientes.js' %}"></script>



{% endblock %}

templates/facturas/factura.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<div class="col">
<div>
<h1>Crear Factura <a href="{% url 'productos' %}" class="btn btn-warning mt-2 me-2 float-end">Salir</a></h1>
</div>
<div class="container-fluid mt-3">
    <div class="row">
    <div class="d-grid gap-4 col-md-8 border-end">
    
    
    <div>
<h2>Agregar Producto</h2>

    <form id="producto-form" method="post">
        {% csrf_token %}
        <Button class="btn btn-outline-success mt-2 rounded-pill float-end" type="submit">
        + Añadir Producto
        </Button>
<table class="table">
    <tr>
        <th>Producto</th>
        <th>Enlace</th>
        <th class="col-1">Cantidad</th>
        
    </tr>
    <tr>
            <td class="col-4"><input class="form-control" type="text" name="nombre_producto" maxlength="200" required id="id_nombre_producto" placeholder="Nombre del Producto"></td>
            <td class="col-4"><input class="form-control" type="text" name="enlace_temu" maxlength="300" required id="id_enlace_temu" placeholder="Enlace de tienda"></td>
            <td class="col-2"><input class="form-control" type="number" name="cantidad" value="1" required id="id_cantidad"></td>        
    </tr><tr>
        <th>Precio</th>
        <th>Peso</th>
        <th>Tipo de Pago</th>
    </tr><tr>
        <td class="col-3">
            <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input class="form-control" type="number" name="precio" value="0" step="0.01" required id="id_precio">
                <span class="input-group-text">USD</span>
            </div>
        </td><td class="col-3">
            <div class="input-group mb-3">
                <input class="form-control" type="number" name="peso" value="0" step="0.01" required id="id_peso">
            <span class="input-group-text">lb</span>
            </div>
        </td>
        <td><select class="form-select" name="tipo_pago" required id="id_tipo_pago" onchange="toggleNotaField()">
            <option value="">---------</option>
            <option value="Pago Completo Inicial">Pago Completo Inicial</option>
            <option value="Mitad/Mitad" selected>Mitad/Mitad</option>
            <option value="Pago Completo Final">Pago Completo Final</option>
            <option value="Otro">Otro</option>
        </td>
    </tr>
    <tr>
        <th><h3>Cambio:</h3></th>
        <td class="col-3">
            
            <div class="form-check">
            <input class="form-check-input" type="radio" name="cambio_radio" id="id_radio_1" value="CUP">
            <div class="input-group col-2">
            <span class="input-group-text">$</span>
            <input class="form-control" type="number" name="cambio_cup" value="0" step="0.01" id="id_cambio_cup"><span class="input-group-text">CUP</span></div></div>
        </td>
        <td class="col-3">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="cambio_radio" id="id_radio_2" value="MLC">
                <div class="input-group col-2">
                <span class="input-group-text">$</span>
            <input class="form-control" type="number" name="cambio_mlc" value="0" step="0.01" id="id_cambio_mlc"><span class="input-group-text">MLC</span></div></div>
        </td>
        
    </tr>
    </table>
    <div id="nota_container" style="display:none;">
        <tr>
            
            <th> <h3>Nota:</h3></th>
            <td colspan="2" class="col-3">
                
                <textarea class="form-control" name="nota" id="id_nota" placeholder="Especificar tipo de pago realizado"></textarea>
            </td>
        </tr>
    </div>
</form>
</div>
</div>
            <div class="col-md-4">
                <div class="container-fluid">
                <h2>Factura: <button id="guardar_factura" class="btn btn-success float-end">Guardar Factura</button></h2>
                
                </div>
                <div id="telefono_container" style="display:none;">
                    <div class="input-group mb-3 mt-3">
                        <span class="input-group-text" id="basic-addon1">+53 </span>
                        <input class="form-control" type="text" id="numero_wsp" placeholder="Número de WhatsApp" required>
                    </div>
                </div>
                
            <hr>
            <div id="factura"></div>
        </div>
            </div>

</div>
</div>


<!-- Modal para opciones después de guardar la factura -->
<div id="successModal" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="close" onclick="closeModal()">&times;</span>
        <p>Factura guardada con éxito.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md">
        <a href="{% url 'facturas' %}" class="btn btn-outline-success btn-sm me-md-2 rounded-pill" id="newInvoiceBtn">Crear nueva factura</a>
        <a href="{% url 'productos' %}" class="btn btn-outline-success btn-sm me-md-2 rounded-pill" id="viewProductsBtn">Regresar a productos</a>
        <a href="{% url 'clientes' %}" class="btn btn-outline-success btn-sm me-md-2 rounded-pill" id="viewProductsBtn">Revisar clientes</a>
    </div>
    </div>
</div>

<style>
    /* Estilos básicos para el modal */
    .modal {
        display: none; 
        position: fixed; 
        z-index: 1; 
        left: 0;
        top: 0;
        width: 100%; 
        height: 100%; 
        overflow: auto; 
        background-color: rgb(0,0,0); 
        background-color: rgba(0,0,0,0.4); 
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; 
        padding: 20px;
        border: 1px solid #888;
        width: 40%; 
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }
</style>

<script>
    function toggleNotaField() {
    const tipoPagoSelect = document.getElementById("id_tipo_pago");
    const notaContainer = document.getElementById("nota_container");

    if (tipoPagoSelect.value === "Otro") {
        notaContainer.style.display = "block";
    } else {
        notaContainer.style.display = "none";
    }
}
</script>
<script src="{% static 'factura.js' %}"></script>


{% endblock %}

templates/facturas/modcliente.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<div class="d-grid gap-4 col-9 mx-auto">
    <form id="eliminar-form" action="{% url 'modcliente' cliente.numero_wsp %}" method="post" style="display:inline;">
        {% csrf_token %}
        <div>
        <input type="hidden" name="eliminar" value="true">
        <button type="button" class="btn btn-danger mt-2 me-2 float-end" onclick="confirmarEliminacion()"><b><img src="{% static 'E262_color.png' %}" alt="25" height="25"></b>Eliminar</button></form>
    <form id="aclualizar-form"action="{% url 'modcliente' cliente.numero_wsp %}"  method="post" style="display:inline;">
    {% csrf_token %}
        <a class="btn btn-close btn-lg" data-bs-toggle="button" href="{% url 'clientes' %}"></a>
        <input type="hidden" name="actualizar" value="true">
        <button class="btn btn-outline-warning mt-2 me-2 float-end" type="submit" onclick="confirmarActualizacion()"><b><img src="{% static '1F504.svg' %}" alt="20" height="20" ></b> Actualizar</button>
        
        
        </div>
        
    
    <br>
    <br>
    
    <table class="table">
        <tr><td>
            <b>Nombre:</b>
        </td><td>
            <b>📱Numero de WSP:</b>
        </td></tr>
        <tr><td>
            {{modificar.nombre}}
        </td><td>
            {{modificar.numero_wsp}}
        </td></tr>
    </table>
</form>
</div>
<script>
    function confirmarEliminacion() {
        if (confirm("¿Estás seguro de que deseas eliminar este cliente? Esta acción no se puede deshacer.")) {
            document.getElementById('eliminar-form').submit();
        }
    }
    function confirmarActualizacion() {
        if (confirm("¿Estás seguro de que deseas modificar este cliente?")) {
            document.getElementById('actualizar-form').submit();
        }
    }
    </script>
{% endblock %}

templates/facturas/modificar-facturas.html
{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<div class="container col">
    <h2>Productos de: {{ cliente.nombre }} <a href="{% url 'clientes' %}" class="btn btn-warning mt-2 me-2 float-end">Salir</a></h2>
    <h4>Factura del: {{ fecha }}</h4>
    <form class="form-control-sm" id="producto-form" method="POST">
        {% csrf_token %}
        <table class="table">
            <thead>
                <tr>
                    <th colspan="2"><h5>Productos</h5></th>
                    <th><h5>Cantidad</h5></th>
                    <th><h5>Precio</h5></th>
                    <th><h5>Cambio</h5></th>
                    <th colspan="3"><h5>Estado</h5></th>
                    
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <td>
                        <input class="form-control" type="text" name="nombre_producto_{{ producto.pk }}" value="{{ producto.nombre_producto }}" required>
                    </td>
                    <td>
                        <input class="form-control" type="text" name="enlace_temu_{{ producto.pk }}" value="{{ producto.enlace_temu }}" required>
                    </td>
                    <td class="col-1">
                        <input class="form-control" type="number" name="cantidad_{{ producto.pk }}" value="{{ producto.cantidad }}" required>
                    </td>
                    <td>
                        <div class="input-group">
                        <span class="input-group-text">$</span>
                        <input class="form-control" type="number" step="0.10" name="precio_{{ producto.pk }}" value="{{ producto.precio }}" required><span class="input-group-text">USD</span></div>
                    </td>
                    <td class="col-2">
                        {% if producto.cambio_cup != 0 %}
                        <div class="input-group">
                            <span class="input-group-text">$</span>
                            <input class="form-control" type="number" name="cambio_cup_{{ producto.pk }}" value="{{ producto.cambio_cup}}" step="0.10" required id="id_cambio_cup">
                            <span class="input-group-text">CUP</span>
                        </div>
                        {% elif producto.cambio_mlc != 0%}
                        <div class="input-group">
                            <span class="input-group-text">$</span>
                            <input class="form-control" type="number" name="cambio_mlc_{{ producto.pk }}" value="{{ producto.cambio_mlc }}" step="0.10" required id="id_cambio_mlc">
                            <span class="input-group-text">MLC</span>
                        </div>
                        {% else %}
                        <b>$0.00</b>
                        {% endif %}
                    </td>
                    <td>
                        <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="encargado_{{ producto.pk }}" id="id_encargado" {% if producto.encargado %}checked{% endif %}> <b>Encargado</b></div>
                    </td><td>
                        <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="recibido_{{ producto.pk }}" id="id_recibido" {% if producto.recibido %}checked{% endif %}> <b>Recibido</b> </div>
                    </td><td>
                        <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="entregado_{{ producto.pk }}" id="id_entregado" {% if producto.entregado %}checked{% endif %}> <b>Entregado</b></div>
                    </td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">Actualizar Productos</button>
    </form>
</div>
<script>
    document.getElementById('producto-form').addEventListener('submit', function(event) {
        if (!confirm('¿Estás seguro de que deseas actualizar todos los productos?')) {
            event.preventDefault(); // Evitar el envío del formulario si el usuario cancela
        }
    });
</script>
{% endblock %}

templates/facturas/modificar.html

{% extends 'Base/base.html' %}
{% load static %}
{% block content %}
<div class="d-grid gap-4 col-9 mx-auto">
    <form id="eliminar-form" action="{% url 'modificar' producto.pk %}" method="post" style="display:inline;">
        {% csrf_token %}
        <div>
        <input type="hidden" name="eliminar" value="true">
        <button type="button" class="btn btn-danger mt-2 me-2 float-end" onclick="confirmarEliminacion()"><b><img src="{% static 'E262_color.png' %}" alt="25" height="25"></b>Eliminar</button></form>
    <form id="aclualizar-form" action="{% url 'modificar' producto.pk %}"  method="post" style="display:inline;">
    
        <a class="btn btn-close btn-lg" data-bs-toggle="button" href="{% url 'productos' %}"></a>
        <input type="hidden" name="actualizar" value="true">
        <button class="btn btn-outline-warning mt-2 me-2 float-end" type="submit" onclick="confirmarActualizacion()"><b><img src="{% static '1F504.svg' %}" alt="20" height="20" ></b> Actualizar</button>
        
        </div>
        
    {% csrf_token %}
    <br>
    <h3>Producto encargado el: {{producto.fecha_formateada}} por {% if producto.factura.nombre != 'Cliente' %}{{producto.factura.nombre}}{% else %}{{producto.factura.numero_wsp}}{% endif %} </h3>
    <table class="table">
        <tr><td class="col-2">
            <b>Cantidad: </b>
        </td><td colspan="2">
            <b>Producto:</b>
        </td><td class="col-3">
            <b>Precio:</b>
        </td></tr>
        <tr><td>
            <input class="form-control" type="number" name="cantidad" value="{{producto.cantidad}}" required id="id_cantidad">
        </td><td class="col-3">
            <input class="form-control" type="text" name="nombre_producto" value="{{producto.nombre_producto}}" maxlength="200" required id="id_nombre_producto">
        </td><td>
            <input class="form-control type="text" name="enlace_temu" value="{{producto.enlace_temu}}" maxlength="300" required id="id_enlace_temu">
        </td><td>
            <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input class="form-control" type="number" name="precio" value="{{producto.precio}}" step="0.01" required id="id_precio">
                <span class="input-group-text">USD</span>
            </div>
        </td></tr>
        <tr><td>
            <b>Peso:</b>
        </td><td colspan="2">
            <b>Cambio:</b>
            
        </td><td>
            <b>Total:</b>
        </td></tr>
        <tr><td>
            <div class="input-group mb-3">
                <input class="form-control" type="number" name="peso" value="{{producto.peso}}" step="0.01" required id="id_peso">
            <span class="input-group-text">lb</span>
            </div>
        </td><td>
            <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input class="form-control" type="number" name="cambio_cup" value="{{producto.cambio_cup}}" step="0.01" required id="id_cambio_cup">
                <span class="input-group-text">CUP</span>
            </div>
        </td><td>
            <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input class="form-control" type="number" name="cambio_mlc" value="{{producto.cambio_mlc}}" step="0.01" required id="id_cambio_mlc">
                <span class="input-group-text">MLC</span>
            </div>
        </td><td>
            <b>${{producto.total}} USD</b>
                {% if producto.cambio_cup != 0 %} <small class="float-end">${{producto.total_cup}} CUP</small>{% endif %}
                {% if producto.cambio_mlc != 0 %}<br> <small class="float-end">${{producto.total_mlc}} MLC</small>{% endif %}
        </td></tr>
        
        <tr><td>
            <b>Metodo de Pago:</b>
        </td><td>
            <select class="form-select" name="tipo_pago" required id="id_tipo_pago" onchange="toggleNotaField()">
                <option value="{{producto.tipo_pago}}">{{producto.tipo_pago}}</option>
                <option value="Pago Completo Inicial">Pago Completo Inicial</option>
                <option value="Mitad/Mitad">Mitad/Mitad</option>
                <option value="Pago Completo Final">Pago Completo Final</option>
                <option value="Otro">Otro</option>
        </td>
            <td>
                <b class="float-end">📱Numero de contacto:</b>
            </td><td class="col-2">
                <select class="form-select" name="factura" required id="id_factura">
                    <option value="{{producto.factura}}">{{producto.factura}}</option>
                    {% for cliente in factura %}
                    {% if cliente.numero_wsp != producto.factura.numero_wsp %}
                    <option value="{{cliente.numero_wsp}}">{{cliente.numero_wsp}}</option>
                    {% endif %}
                    {% endfor %}
            </td>
    
    </tr>
    <tr><td>
        <b>Estado:</b>
    </td><td>
        {{modificar.encargado}} <b>Encargado</b> 
    </td><td>
        {{modificar.recibido}} <b>Recibido</b> 
    </td><td>
        {{modificar.entregado}} <b>Entregado</b>
    </td></tr>
    {% if producto.tipo_pago == 'otro' %}
    <tr>
        <th>Nota:</th>
        <td colspan="4"><textarea class="form-control" name="nota" id="id_nota" {% if producto.nota == "" %}placeholder="Especificar tipo de pago realizado o algun otro comentario si lo desea"{% endif %}>{{producto.nota}}</textarea> </td>
    </tr>
    {% endif %}
    </table>
    <input type="hidden" name="id" id="" value="{{product.pk}}" readonly>
</form>
<hr>
{% if anterior == 0 %}
{% if siguiente %}
<div>
    <a class="btn btn-success mt-2 float-end" href="{% url 'modificar' siguiente %}">Siguiente <span aria-hidden="true">&raquo;</span></a>
</div>
{% endif %}
{% else %}
<div>
    <a class="btn btn-success mt-2" href="{% url 'modificar' anterior %}"><span aria-hidden="true">&laquo;</span> Anterior</a>
    {% if siguiente %}
    <a class="btn btn-success mt-2 float-end" href="{% url 'modificar' siguiente %}">Siguiente <span aria-hidden="true">&raquo;</span></a>
    {% endif %}
</div>
{% endif %}
</div>
<script>
    function confirmarEliminacion() {
        if (confirm("¿Estás seguro de que deseas eliminar este producto? Esta acción no se puede deshacer.")) {
            document.getElementById('eliminar-form').submit();
        }
    }
    function confirmarActualizacion() {
        if (confirm("¿Estás seguro de que deseas modificar este producto?")) {
            document.getElementById('actualizar-form').submit();
        }
    }
    </script>
{% endblock %}

templates/facturas/productos.html
{% extends 'Base/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %}
<div class="col">
<div class="mt-3">
    <h2>Lista de Productos <a href="{% url 'facturas' %}" class="btn btn-outline-success me-2 rounded-pill float-end" type="button"><b>+</b> Añadir Factura</a></h2>
</div>
    <div class="d-flex justify-content-md-end me-2">
        <form class="form-inline" method="post">
            {% csrf_token %}
            <input type="hidden" name="form_name" value="form4">
            <div class="input-group col-1 rounded-pill">  <!-- Ampliar el ancho del input -->
                <input type="date" name="fecha" class="form-control rounded-pill rounded-end " value="{{ fecha_seleccionada|date:'Y-m-d' }}">
                <button type="submit" class="btn btn-outline-dark rounded-pill rounded-start">Filtrar</button>
            </div>
        </form>
    
  <form class="form" method="post">
    {% csrf_token %}
    <input type="hidden" name="form_name" value="form1">
        <button>
          <svg width="17" height="16" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="search">
              <path d="M7.667 12.667A5.333 5.333 0 107.667 2a5.333 5.333 0 000 10.667zM14.334 14l-2.9-2.9" stroke="currentColor" stroke-width="1.333" stroke-linecap="round" stroke-linejoin="round"></path>
          </svg>
        </button>
        <input class="input" placeholder="Buscar" required="" type="text" name="buscar">
        <button class="reset" type="reset">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
      </button>
  </form>
  <form method="post" class="form-inline">
    {% csrf_token %}
    <input type="hidden" name="form_name" value="form3">
    <div class="input-group col-1 rounded-pill">
    <select name="estado" class="form-select rounded-pill rounded-end">
        <option value="por encargar" {% if estado_actual == "por encargar" %}selected{% endif %}>Por encargar</option>
        <option value="encargado" {% if estado_actual == "encargado" %}selected{% endif %}>Encargado</option>
        <option value="recibido" {% if estado_actual == "recibido" %}selected{% endif %}>Recibido</option>
        <option value="entregado" {% if estado_actual == "entregado" %}selected{% endif %}>Entregado</option>
        <option value="" {% if estado_actual == "" %}selected{% endif %}>Todos</option>
    </select>
    <button type="submit" class="btn btn-outline-dark rounded-pill rounded-start">Filtrar</button>
</div>

</form>  
</div> 



<div>
    {% for fecha in fechas %}
        {% if productos_por_fecha|get_item:fecha %}
        <div class="d-flex justify-content-between mt-4">  
        <div class="h2 me-4">{{ fecha }}</div> <div class="progress mt-2 me-4 col-4 aling-items-end" role="progressbar" aria-label="Progress bar" aria-valuenow="{{ progreso|get_item:fecha|floatformat:0 }}" aria-valuemin="0" aria-valuemax="100" style="height: 25px;">
                <div class="progress-bar progress-bar-striped progress-bar-animated {% if progreso|get_item:fecha|floatformat:0 < '75' %}bg-success{% elif progreso|get_item:fecha|floatformat:0 < '90' %}bg-warning{% else %}bg-danger{% endif %}" style="width: {{ progreso|get_item:fecha|floatformat:0 }}%">
                    <b>{{ dias|get_item:fecha }} días</b>
                </div>
            </div>
        </div>  
            <table class="table">
                <tr>
                    <th scope="col" class="col-2">Contacto:</th>
                    <th scope="col" colspan="3" class="col-6">Productos:</th>
                    <th scope="col" class="col-1">Total:</th>
                    <th scope="col" class="col-2">Tipo de Pago:</th>
                    <th scope="col" colspan="5">Estado:</th>
                </tr>
                <tbody>
                    {% for product in productos_por_fecha|get_item:fecha %}
                        <tr>
                            <td class="col-2">
                                {% if product.factura.nombre != "Cliente" %}
                                    <a class="btn btn-outline-success" href="http://wa.me/53{{ product.factura.numero_wsp }}">📱 {{ product.factura.nombre }}</a>
                                {% else %}
                                    <a class="btn btn-outline-success" href="http://wa.me/53{{ product.factura.numero_wsp }}">📱 {{ product.factura.numero_wsp }}</a>
                                {% endif %}
                            </td>
                            <td class="col-1">{{ product.cantidad }}</td>
                            <td class="col-2">{{ product.nombre_producto }}</td>
                            <td class="col-3"><a href="{{ product.enlace_temu }}">{{ product.enlace_temu }}</a></td>
                            <td class="col-1">${{ product.total }}</td>
                            <td class="col-2">{{ product.tipo_pago }}</td>
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" name="form_name" value="form2">
                                <input type="hidden" name="id" value="{{ product.pk }}" readonly>
                                <input type="hidden" name="estado_actual" value="{{ estado_actual }}">
                                <td>{% if product.encargado %}Encargado:<img src="{% static '2705.svg' %}" alt="30" height="30">{% else %}Encargado: {{ estado.encargado }}{% endif %}</td>
                                <td>{% if product.recibido %}Recibido:<img src="{% static '2705.svg' %}" alt="30" height="30">{% else %}Recibido: {{ estado.recibido }}{% endif %}</td>
                                <td>{% if product.entregado %}Entregado:<img src="{% static '2705.svg' %}" alt="30" height="30">{% else %}Entregado: {{ estado.entregado }}{% endif %}</td>
                                <td><input class="btn btn-success btn-sm" type="submit" value="Actualizar"></td>
                            </form>
                            <td>
                                <a class="btn btn-success btn-sm" href="{% url 'modificar' product.pk %}">Modificar</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    {% endfor %}
</div>
</div>
{% endblock %}